---
apiVersion: v1
kind: Namespace
metadata:
  name: stress-ns
...

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cpu-stress-test
  namespace: stress-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
        - name: stress-cpu
          image: mak3r/stress-armv8
          command: ["stress"]
          args: ["--cpu", "1"]
      restartPolicy: Always
...